spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://user-play.icu:3306/user_center?useSSL=no'
    username: root
    password: 123456
  # 设置session超时时间
  session:
    timeout: 86400
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true