spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://8.134.134.94:3306/?useSSL=no'
    username: root
    password: 123456
  # 设置session超时时间
  session:
    timeout: 86400
  redis:
    host: 8.134.134.94
    port: 6379
    database: 1
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true
